export const COLOR_MONEY = "#edd500";
export const COLOR_EXP = "rgba(144,202,249,1)";
export const COLOR_EXP_RGBA = (opacity: number) => COLOR_EXP.replace("1)", `${opacity})`);
export const COLOR_SKILLPOINT = "#57b4ff";
export const COLOR_DMG = "red";
export const COLOR_PLAYER = "#ed8300";
export const COLOR_HP_BAR_RED = "red";
export const COLOR_HP_BAR_GREEN = "#36e400";
export const COLOR_HP_GREEN = "#3cff00";
export const COLOR_MENU_BACKGROUND = "#ded4b2";
export const COLOR_STAT_BONUS_BLUE = "rgba(2,166,255,1)";
export const COLOR_STAT_BONUS_BLUE_RGBA = (opacity: number) => COLOR_STAT_BONUS_BLUE.replace("1)", `${opacity})`);
export const COLOR_STAT_BONUS_ORANGE = "#ed6400";
export const COLOR_SELECTED = "#4f97d1";
export const COLOR_GUN_SELECTED = "#4f97d1";
export const COLOR_LEVEL = "#62abe6";
export const COLOR_MAP_BACKGROUND = "#eeeeee";
export const COLOR_SHOP = "#26a200";
