export const standardMap = [
  "xx                  ",
  "x           x       ",
  "            xxxxxx  ",
  "                    ",
  "                    ",
  "    xxxxxxxxxx      ",
  "             x      ",
  "             x      ",
  "       x     x      ",
  "       x     x      ",
  "       x     x      ",
  "       x            ",
  "       xxx     xxxxx",
  "                    ",
  "                    ",
];
