export const straightMap = [
  "                    ",
  "                    ",
  "                    ",
  "                    ",
  "                    ",
  "                    ",
  "                    ",
  "xxxxxxxxxxxxxxxxxxx ",
  "                  xx",
  "                    ",
  "                    ",
  "                    ",
  "                    ",
  "                    ",
  "                    ",
];

export const standardMap = [
  "         ~~~~~~~~~~~",
  "         ~~~~xxxxxxx",
  "         ~~~~x~~^^^^",
  "             x ~^^^^",
  "             xxxxx  ",
  "               ~ x  ",
  "xxxxxxxxxxx    ~ x  ",
  "          x    ~ x  ",
  "      xxxxx    ~ x  ",
  "      x ^^^    ~ x  ",
  "      x  ^^  xxxxx  ",
  "      x      x ~    ",
  "      xxxxxxxx ~~~~~",
  "               ~~~~~",
  "               ~~~~~",
];

export const penisMap = [
  "                    ",
  "         xxx        ",
  "       xx   xx      ",
  "      xx     xx     ",
  "      xx     xx     ",
  "      xxxxxxxxx     ",
  "      x       x     ",
  "      x       x     ",
  "      x       x     ",
  "      x       x     ",
  "      x       x     ",
  "      x       x     ",
  " xxxx x       x xxxx",
  "xx  xxx       xxx   ",
  "                    ",
];
